### ISSUE TITLE
TASK: [rvm_io.rvm1-ruby | Install rubies] stucks

### ISSUE THREAD

**Issue by evserykh** [rvm/rvm1-ansible#38]
I have playbook: 

```ruby
roles:
  - role: rvm_io.rvm1-ruby
    rvm1_install_flags:       '--auto-dotfiles --user-install
    rvm1_install_path:        '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_rubies: 
      - '2.1.5'
    sudo:                     True
    rvm1_user:                'user'
```

I try to execute
```
ansible-playbook playbook.yml --ask-become-pass
```

and RVM log shows installation process stops and waits for password
```
...
...
...
++ sudo -p '%p password required for '\''apt-get --quiet --yes update'\'': ' apt-get --quiet --yes update
```

When I try to install ruby without
```
rvm1_user:                'user'
```
the Ruby installs fine, but TASK: [rvm_io.rvm1-ruby | Select default ruby] failed with Permission denied because ~/.rvm belongs to root

**Comment by nickjj** [comment]
What happens if you set `sudo_user: 'user'` when you run the role?

**Comment by rafadc** [comment]
Same problem here in an Ubuntu machine in Digital Ocean

Doing sudo_user: 'user' made no difference.

I'm installing RVM for a user that is not sudoer but connecting with root and using sudo_user to change to that user. Then I suppose that when RVM is installed it can't change back to root to install dependencies.

The same problem happens when you make the user sudoer but he needs a password.

The task runs flawlessly for me if I before applying the role I do the following

```
- name: Make the user sudoer with no password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%myuser' line='%myuser ALL=(ALL) NOPASSWD: ALL'"
```

Unfortunately I could not find any way of asking rvm about which packages it needs to install them before using root user.

Thanks a lot!

Thanks a lot!

**Comment by nickjj** [comment]
Ok, I'm going to close it for now. No prob, I'm glad you got things squared away for your use case.
