### ISSUE TITLE
role fails with --check flag

### ISSUE THREAD

**Issue by bjallen** [rvm/rvm1-ansible#9]
Running a playbook with this role in --check mode seems to always fail. This is running against Ubuntu systems of different versions.

ansible 1.7.1

TASK: [rvm_io.rvm1-ruby | ensure rvm is upgraded] ***************************** 
fatal: [host_name] => error while evaluating conditional: rvm_binary.stat.exists and rvm_stable_version_number.content | default(rvm1_rvm_stable_version_number) | replace('\n', '') > rvm_current_version.stdout.split()[1]

Maybe I'm just missing something simple.

**Comment by trinitronx** [comment]
Configuration Managment tools such as Ansible, Puppet, and Chef each have their own equivalent of a dry-run check mode (Ansible: `--check`, Chef: `--why-run`, Puppet: `--noop`).  And each have their own issues.  Namely:  They can't guarantee that variables or resources on the system which are dependent on the previous state of the system will be exactly simulated in these modes.  They each will either fail in their own way, or do a best-effort to [lie to you][1] about the simulated state of the system when your playbooks/roles, cookbooks, or manifests are written in such a way to depend on the output of previous steps (state of your system) in your config managment scripts.

For example, if you set a variable based on the result of a previous step, and then check it later or do something with it later... it will usually fail when run in dry run mode.  Sometimes there are things you can do to avoid this, or fake it (Chef: You can fake things by checking `Chef::Config[:why_run]`, add helper methods to your LWRPs [`whyrun_supported?`][5], [Chefspec][2] has great mock capability, Ansible: you can _try_ to use [`always_run: true`][3] on the steps that register vars).  However, each tool is nowhere near perfect, and cannot guarantee that the scripts you write will always be runnable in dry-run mode.

Hence, there becomes a need for integration-level testing, and tools such as [test-kitchen][4].

[1]: http://blog.afistfulofservers.net/post/2012/12/21/promises-lies-and-dryrun-mode/
[2]: https://docs.chef.io/chefspec.html
[3]: http://docs.ansible.com/playbooks_checkmode.html#running-a-task-in-check-mode
[4]: http://kitchen.ci/
[5]: https://docs.chef.io/lwrp_custom_provider.html#whyrun-supported

**Comment by nickjj** [comment]
Going to close this for now. If anything ever comes out of this please open a new ticket @bjallen.

**Comment by Zeelot** [comment]
Wanted to suggest we at least improve this issue a bit. It's true that trying to run ansible with `--check` on a brand new instance will most likely fail on all sorts of steps. Files are missing, packages don't exist yet (missing apt repos), etc. There are way too many things missing to properly run with `--check`.

However, we can make this role run with `--check` on a provisioned machine. This allows us to quickly see "what has changed since I last provisioned the machine?" without running into errors in this role.

If we change these three tasks:

- https://github.com/rvm/rvm1-ansible/blob/master/tasks/rubies.yml#L3
- https://github.com/rvm/rvm1-ansible/blob/master/tasks/rubies.yml#L17
- https://github.com/rvm/rvm1-ansible/blob/master/tasks/rubies.yml#L47

To include `always_run: true`, then we should have the needed registered variables to get through the role without actually causing changes. Thoughts?

**Comment by Pepan** [comment]
It still happens with --check.
TASK: [rvm | Install rubies] ************************************************** 
fatal: [192.168.0.7] => error while evaluating conditional: rvm1_rubies and item.rc != 0
